In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
print("Selamat Datang")

Selamat Datang


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy adalah library python digunakan untuk komputasi matriks. 
Matplotlib adalah library python untuk presentasi data berupa grafik atau plot. Pandas biasa digunakan untuk membuat tabel, mengubah dimensi data, mengecek data, dan lain sebagainya.

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 nan]
 ['Germany' 50.0 54000.0]
 ['Spain' nan 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 65750.0]
 ['Germany' 50.0 54000.0]
 ['Spain' 41.375 61000.0]
 ['Germany' 40.0 65750.0]
 ['France' 35.0 58000.0]
 ['Spain' 41.375 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 65750.0]
 [0.0 1.0 0.0 50.0 54000.0]
 [0.0 0.0 1.0 41.375 61000.0]
 [0.0 1.0 0.0 40.0 65750.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 41.375 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 1 0 1 1 1 0 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 41.375 52000.0]
 [0.0 1.0 0.0 40.0 65750.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 41.375 61000.0]
 [0.0 0.0 1.0 27.0 65750.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 50.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[1 1 0 0 0 0 0 1]


In [ ]:
print(y_test)

[1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 0.07789728266268395 -1.535218708119311]
 [0.0 1.0 0.0 -0.12371921364073332 -0.13377424427595655]
 [1.0 0.0 0.0 0.4628015028782987 0.5032459665619318]
 [0.0 0.0 1.0 0.07789728266268395 -0.6179096045127517]
 [0.0 0.0 1.0 -2.0299115423275875 -0.13377424427595655]
 [1.0 0.0 0.0 1.0493222193973308 1.2167086027003668]
 [0.0 1.0 0.0 1.3425825776568467 1.6244015376366154]
 [1.0 0.0 0.0 -0.8568701092895233 -0.9236793057149382]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 1.3425825776568467 -1.3313722406511868]
 [1.0 0.0 0.0 -0.5636097510300073 -0.006370202108378883]]
